### PR TITLE
Downgrade flutter version to work with beta 3

### PR DESCRIPTION
**Pull request by fuzzybinary**
Flutter Beta 3 is 0.3.2, and it looks like lottie works with it properly, so I'd like to downgrade the required version in the yaml to >=0.3.2

### CODE REVIEW

**Comment by dnfield** [comment]
It won't work properly - I'm not sure what you tested with, but there are several places where we have to call `Path.getBounds` and `Path.computeMetrics`, which are not available until 0.3.6.

**Comment by dnfield** [comment]
Or, perhaps I'm speaking too quickly.

If you want to downgrade to 0.3.2, you have to also remove any references to functionality that doesn't exist there yet - like all the calls to `Path.getBounds` and `Path.computeMetrics` - including in the path_drawing dependency.

There are probably some Lottie files that will work without that, but I don't feel comfortable with a release for this that would lead to crashes like that for many Lottie files.  I'd consider a patch to a separate branch that does something like that.

**Comment by fuzzybinary** [comment]
Ah, sorry, I jumped the gun on that. I figured it was a typo, but you're right, I was using an animation that wasn't using those calls.

**Comment by dnfield** [comment]
I'd make the effort but my gut says by the time it was sorted out 0.3.6 or greater would be in beta

**Pull request closed without merging**
